spring:
  liquibase:
    change-log: "classpath:db/changelog/vine-changelog.xml"

  datasource:
    url: jdbc:mysql://localhost:3306/vine_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver



#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL:
          trace
        orm:
          jdbc:
            bind:
              trace

#  logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#logging:
#  level:
#    org:
#      hibernate: debug
#      springframework:
#        debug
#    sql: debug
#    root: debug